### ISSUE TITLE
Add support for Xcode 9.3 coverage reports

### ISSUE THREAD

**Issue by thelvis4** [fastlane-community/xcov-core#12]
As specified in [Release Notes](https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta_3/Release_Notes_for_Xcode_9.3_beta_3.pdf), Xcode 9.3 comes with a new format for coverage reports together with a CLI tool (`xccov`) that can convert `.xccovreport` files to JSON.
We can use Xcode's `xccov` (call it from `xcov-core`) to support new coverage reports while maintaining the support for the older format. The resulted JSON will be passed to `xcov` which will continue to do its thing.
Just have to make the same JSON schema is used for both coverage formats.
@nakiostudio Any thoughts?

**Comment by nakiostudio** [comment]
Hi @thelvis4 👋 

Sorry for the late response, I haven't had time to test the Xcode beta until last night. I did some debugging and what xccov does is not very different to what xcov-core was doing before. Actually with few changes xcov-core is able to open `xccovreport` files so I think we can ignore `xccov` as it doesn't add much value.

However, the changes on how `IDESchemeActionCodeCoverageFile` is unarchived make keeping both `xccoverage` and `xccovreport` support a bit difficult so I've come up with a solution that relies on `IDEFoundation` for this unarchiving. 

The problem with this approach is that it creates a dependency between xcov-core and having Xcode in the machine it runs on.

Let me know what you think.

https://github.com/nakiostudio/xcov-core/pull/13

**Comment by RodBrown1988** [comment]
Would be great to see some action on this issue - currently blocking us from upgrading to Xcode 9.3 on a CI I work with.

**Comment by nakiostudio** [comment]
Hi @RodBrown1988 👋 

This is pretty much done, need to complete some testing and will release a new version soon.

**Comment by nakiostudio** [comment]
Version `1.4.0` should bring xcov back to life :)
